"""Add unique key constraint to resume_submission table

Revision ID: 9dda918f3fba
Revises: 5bbc8b8ae19c
Create Date: 2023-08-10 00:25:36.865535

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "9dda918f3fba"
down_revision = "5bbc8b8ae19c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "ak_user_question",
        "resume_submission",
        ["user_id", "question_id", "recruiting_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ak_user_question", "resume_submission", type_="unique")
    # ### end Alembic commands ###
