"""Alter announcement content column type to Text

Revision ID: dafb8370274a
Revises: 9ce549ecac1e
Create Date: 2023-08-04 01:10:41.478741

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "dafb8370274a"
down_revision = "9ce549ecac1e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "announcement",
        "content",
        existing_type=mysql.VARCHAR(length=10000),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "announcement",
        "content",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=10000),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
