"""add recruiting type

Revision ID: 9ce549ecac1e
Revises: 36772986ccbf
Create Date: 2023-08-01 20:29:57.622366

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "9ce549ecac1e"
down_revision = "36772986ccbf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recruiting",
        sa.Column(
            "type",
            sa.Enum("ROOKIE", "DESIGNER", "PROGRAMMER", name="recruitingtype"),
            server_default=sa.text("'ROOKIE'"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recruiting", "type")
    # ### end Alembic commands ###
