"""add language and status column

Revision ID: e66fd72f60dc
Revises: 8af5f11b61da
Create Date: 2023-07-23 04:01:43.531893

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "e66fd72f60dc"
down_revision = "8af5f11b61da"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "code_submission",
        sa.Column(
            "language",
            sa.Enum(
                "C",
                "CPP",
                "JAVA",
                "JAVASCRIPT",
                "PYTHON",
                "RUBY",
                "GO",
                "TYPESCRIPT",
                "KOTLIN",
                "SCALA",
                "SQL",
                "SWIFT",
                name="language",
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "code_submission",
        sa.Column(
            "status",
            sa.Enum("RUNNING", "SOLVED", "WRONG", name="codesubmissionstatus"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("code_submission", "status")
    op.drop_column("code_submission", "language")
    # ### end Alembic commands ###
