"""Add testcase resource limit columns

Revision ID: a3cacde08168
Revises: 79d431037047
Create Date: 2023-07-27 00:17:52.238197

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "a3cacde08168"
down_revision = "79d431037047"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "testcase",
        sa.Column(
            "extra_time",
            sa.Numeric(precision=10, scale=5),
            server_default=sa.text("'0.00000'"),
            nullable=False,
        ),
    )
    op.add_column(
        "testcase",
        sa.Column(
            "memory_limit",
            sa.Integer(),
            server_default=sa.text("128000"),
            nullable=False,
        ),
    )
    op.add_column(
        "testcase",
        sa.Column(
            "stack_limit", sa.Integer(), server_default=sa.text("64000"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("testcase", "stack_limit")
    op.drop_column("testcase", "memory_limit")
    op.drop_column("testcase", "extra_time")
    # ### end Alembic commands ###
