"""Add foreign key to problem which refer to recruiting

Revision ID: 51ee6d9fff87
Revises: b06b459ca8b9
Create Date: 2023-07-23 00:04:20.724322

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "51ee6d9fff87"
down_revision = "b06b459ca8b9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("problem", sa.Column("recruiting_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "problem", "recruiting", ["recruiting_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "problem", type_="foreignkey")
    op.drop_column("problem", "recruiting_id")
    # ### end Alembic commands ###
