"""Set nullable False of contents and answer of resume

Revision ID: dc762d71dbf3
Revises: 51ee6d9fff87
Create Date: 2023-07-23 01:45:29.628096

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "dc762d71dbf3"
down_revision = "51ee6d9fff87"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "resume_question",
        "content",
        existing_type=mysql.VARCHAR(length=10000),
        nullable=False,
    )
    op.alter_column(
        "resume_submission",
        "answer",
        existing_type=mysql.VARCHAR(length=10000),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "resume_submission",
        "answer",
        existing_type=mysql.VARCHAR(length=10000),
        nullable=True,
    )
    op.alter_column(
        "resume_question",
        "content",
        existing_type=mysql.VARCHAR(length=10000),
        nullable=True,
    )
    # ### end Alembic commands ###
