"""Add created_at and updated_at columns to resume_question

Revision ID: a246ed554bd3
Revises: b06b459ca8b9
Create Date: 2023-07-25 01:55:43.223506

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "a246ed554bd3"
down_revision = "b06b459ca8b9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resume_question",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.add_column(
        "resume_question",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resume_question", "updated_at")
    op.drop_column("resume_question", "created_at")
    # ### end Alembic commands ###
