"""Alter code_submission, recruiting, resume_question, resume_submission


Revision ID: 79d431037047
Revises: a246ed554bd3
Create Date: 2023-07-26 00:22:15.210331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "79d431037047"
down_revision = "a246ed554bd3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "code_submission",
        sa.Column(
            "language",
            sa.Enum(
                "C",
                "CPP",
                "JAVA",
                "JAVASCRIPT",
                "PYTHON",
                "RUBY",
                "GO",
                "TYPESCRIPT",
                "KOTLIN",
                "SCALA",
                "SQL",
                "SWIFT",
                name="language",
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "code_submission",
        sa.Column(
            "status",
            sa.Enum("RUNNING", "SOLVED", "WRONG", name="codesubmissionstatus"),
            nullable=False,
        ),
    )
    op.add_column("problem", sa.Column("recruiting_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "problem", "recruiting", ["recruiting_id"], ["id"], ondelete="SET NULL"
    )
    op.alter_column(
        "recruiting",
        "description",
        existing_type=mysql.VARCHAR(length=10000),
        type_=sa.Text(),
        nullable=False,
    )
    op.alter_column(
        "resume_question",
        "content",
        existing_type=mysql.VARCHAR(length=10000),
        type_=sa.Text(),
        nullable=False,
    )
    op.alter_column(
        "resume_submission",
        "answer",
        existing_type=mysql.VARCHAR(length=10000),
        type_=sa.Text(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "resume_submission",
        "answer",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=10000),
        nullable=True,
    )
    op.alter_column(
        "resume_question",
        "content",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=10000),
        nullable=True,
    )
    op.alter_column(
        "recruiting",
        "description",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=10000),
        nullable=True,
    )
    op.drop_constraint(None, "problem", type_="foreignkey")
    op.drop_column("problem", "recruiting_id")
    op.drop_column("code_submission", "status")
    op.drop_column("code_submission", "language")
    # ### end Alembic commands ###
