"""fix typo in column name

Revision ID: 6eb442d2b80e
Revises: a3cacde08168
Create Date: 2023-07-28 00:25:09.208899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "6eb442d2b80e"
down_revision = "a3cacde08168"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "code_submission",
        column_name="create_at",
        new_column_name="created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "code_submission",
        column_name="created_at",
        new_column_name="create_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        nullable=False,
    )
    # ### end Alembic commands ###
