"""Add ERROR to CodeSubmission status

Revision ID: 074873a1c19a
Revises: dafb8370274a
Create Date: 2023-08-05 01:08:26.894674

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "074873a1c19a"
down_revision = "dafb8370274a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "code_submission",
        "status",
        existing_type=mysql.ENUM("RUNNING", "SOLVED", "WRONG", "ERROR"),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "code_submission",
        "status",
        existing_type=mysql.ENUM("RUNNING", "SOLVED", "WRONG"),
        nullable=False,
    )
    # ### end Alembic commands ###
