"""initialize database
Add table
user, announcement, recruiting, resume_submission, resume_question,
problem, testcase, code_submission, code_submission_result

Revision ID: 3fdaee6050ce
Revises:
Create Date: 2023-07-21 18:23:29.715742
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "3fdaee6050ce"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "announcement",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=50), nullable=True),
        sa.Column("content", sa.String(length=10000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "problem",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("num", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recruiting",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("from_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("to_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("description", sa.String(length=10000), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sso_id", sa.String(length=50), nullable=True),
        sa.Column("first_name", sa.String(length=30), nullable=False),
        sa.Column("last_name", sa.String(length=30), nullable=False),
        sa.Column("phone_number", sa.String(length=30), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("department", sa.String(length=50), nullable=True),
        sa.Column("college", sa.String(length=50), nullable=True),
        sa.Column("university", sa.String(length=50), nullable=True),
        sa.Column("github_email", sa.String(length=255), nullable=True),
        sa.Column("slack_email", sa.String(length=255), nullable=True),
        sa.Column("notion_email", sa.String(length=255), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "code_submission",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("problem_id", sa.Integer(), nullable=True),
        sa.Column(
            "create_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["problem_id"], ["problem.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "resume_question",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recruiting_id", sa.Integer(), nullable=True),
        sa.Column("question_num", sa.Integer(), nullable=False),
        sa.Column("content_limit", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(length=10000), nullable=True),
        sa.ForeignKeyConstraint(
            ["recruiting_id"], ["recruiting.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "testcase",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("problem_id", sa.Integer(), nullable=True),
        sa.Column("stdin", sa.Text(), nullable=False),
        sa.Column("expected_output", sa.Text(), nullable=False),
        sa.Column("time_limit", sa.Numeric(precision=10, scale=5), nullable=False),
        sa.Column("is_example", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["problem_id"], ["problem.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "code_submission_result",
        sa.Column("submission_id", sa.Integer(), nullable=False),
        sa.Column("testcase_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["submission_id"], ["code_submission.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["testcase_id"], ["testcase.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("submission_id", "testcase_id"),
    )
    op.create_table(
        "resume_submission",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("question_id", sa.Integer(), nullable=True),
        sa.Column("recruiting_id", sa.Integer(), nullable=True),
        sa.Column("answer", sa.String(length=10000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["question_id"], ["resume_question.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["recruiting_id"], ["recruiting.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resume_submission")
    op.drop_table("code_submission_result")
    op.drop_table("testcase")
    op.drop_table("resume_question")
    op.drop_table("code_submission")
    op.drop_table("user")
    op.drop_table("recruiting")
    op.drop_table("problem")
    op.drop_table("announcement")
    # ### end Alembic commands ###
