"""CodeSubmissionResult 에 status, time, memory 추가

Revision ID: 101ccb508ee1
Revises: a9920d488658
Create Date: 2024-08-09 11:53:13.297092

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "101ccb508ee1"
down_revision = "a9920d488658"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "code_submission_result",
        sa.Column(
            "status",
            sa.Enum(
                "RUNNING",
                "CORRECT",
                "WRONG",
                "COMPILE_ERROR",
                "RUNTIME_ERROR",
                "TIME_LIMIT_EXCEEDED",
                "MEMORY_LIMIT_EXCEEDED",
                "INTERNAL_SERVER_ERROR",
                name="codesubmissionresultstatus",
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "code_submission_result", sa.Column("time", sa.Float(), nullable=True)
    )
    op.add_column(
        "code_submission_result", sa.Column("memory", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("code_submission_result", "memory")
    op.drop_column("code_submission_result", "time")
    op.drop_column("code_submission_result", "status")
    # ### end Alembic commands ###
