"""add pre_registration table

Revision ID: 9dd2ff558a82
Revises: c9b5e993e78b
Create Date: 2025-07-18 21:04:38.078619

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "9dd2ff558a82"
down_revision = "c9b5e993e78b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pre_registration",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=255), nullable=False),
        sa.Column("generation", sa.String(length=30), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pre_registration")
    # ### end Alembic commands ###
