"""fix sponsored_date type

Revision ID: f1532cef4ac5
Revises: 16b579609e97
Create Date: 2025-08-25 21:42:00.063456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "f1532cef4ac5"
down_revision = "16b579609e97"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sponsor",
        "sponsored_date",
        existing_type=mysql.DATETIME(),
        type_=sa.Date(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sponsor",
        "sponsored_date",
        existing_type=sa.Date(),
        type_=mysql.DATETIME(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
