"""fix: enum type

Revision ID: e974b1acbdc9
Revises: 84b2b60d89a6
Create Date: 2025-07-10 12:11:29.679370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "e974b1acbdc9"
down_revision = "84b2b60d89a6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "seminar",
        "seminar_type",
        existing_type=mysql.ENUM("SPRING", "FAST_API", "FRONTEND", "ANDROID", "IOS"),
        type_=sa.Enum(
            "SPRING", "FASTAPI", "FRONTEND", "ANDROID", "IOS", name="seminartype"
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "seminar",
        "seminar_type",
        existing_type=sa.Enum(
            "SPRING", "FASTAPI", "FRONTEND", "ANDROID", "IOS", name="seminartype"
        ),
        type_=mysql.ENUM("SPRING", "FAST_API", "FRONTEND", "ANDROID", "IOS"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
