"""thumbnail image로 변경

Revision ID: 86732184f087
Revises: c29ee28051da
Create Date: 2025-10-05 15:55:12.182506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "86732184f087"
down_revision = "c29ee28051da"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project", sa.Column("thumbnail_image_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "project", "project_image", ["thumbnail_image_id"], ["id"]
    )
    op.drop_column("project", "thumbnail_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project", sa.Column("thumbnail_url", mysql.VARCHAR(length=255), nullable=True)
    )
    op.drop_constraint(None, "project", type_="foreignkey")
    op.drop_column("project", "thumbnail_image_id")
    # ### end Alembic commands ###
