"""add history_unit

Revision ID: 60e3aaf301ce
Revises: 564952e2cd49
Create Date: 2025-11-27 21:52:29.877472

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "60e3aaf301ce"
down_revision = "564952e2cd49"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "history", sa.Column("history_unit", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("history", "history_unit")
    # ### end Alembic commands ###
