"""recruiting info date_info 타입 변경

Revision ID: c29ee28051da
Revises: 0485bca82700
Create Date: 2025-09-29 16:14:48.611850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "c29ee28051da"
down_revision = "0485bca82700"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "recruiting_info",
        "date_info",
        existing_type=mysql.DATETIME(),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "recruiting_info",
        "date_info",
        existing_type=sa.String(length=50),
        type_=mysql.DATETIME(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
