"""fix typo

Revision ID: f656d4e56c64
Revises: 066dac40ece1
Create Date: 2025-07-06 18:08:09.939208

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "f656d4e56c64"
down_revision = "066dac40ece1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column(
            "project_type",
            sa.Enum("SERVICE", "STUDY", name="projecttype"),
            nullable=False,
        ),
    )
    op.drop_column("project", "service_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column("service_type", mysql.ENUM("SERVICE", "STUDY"), nullable=False),
    )
    op.drop_column("project", "project_type")
    # ### end Alembic commands ###
