"""change text to mediumtext

Revision ID: 8e8f3767416a
Revises: b306477282a1
Create Date: 2025-08-03 20:56:21.389199

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "8e8f3767416a"
down_revision = "b306477282a1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "testcase",
        "stdin",
        existing_type=mysql.TEXT(),
        type_=mysql.MEDIUMTEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "testcase",
        "expected_output",
        existing_type=mysql.TEXT(),
        type_=mysql.MEDIUMTEXT(),
        existing_nullable=False,
    )
    op.drop_column("timeline", "category")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "timeline", sa.Column("category", mysql.VARCHAR(length=30), nullable=False)
    )
    op.alter_column(
        "testcase",
        "expected_output",
        existing_type=mysql.MEDIUMTEXT(),
        type_=mysql.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "testcase",
        "stdin",
        existing_type=mysql.MEDIUMTEXT(),
        type_=mysql.TEXT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
