"""fix history table

Revision ID: d7157419824c
Revises: 22f4d37c8e9f
Create Date: 2025-07-12 23:06:01.005810

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "d7157419824c"
down_revision = "22f4d37c8e9f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "histroy", sa.Column("history_key", sa.String(length=50), nullable=False)
    )
    op.add_column(
        "histroy", sa.Column("history_value", sa.String(length=50), nullable=False)
    )
    op.drop_column("histroy", "total_projects")
    op.drop_column("histroy", "total_users")
    op.drop_column("histroy", "total_members")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "histroy",
        sa.Column(
            "total_members",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "histroy",
        sa.Column(
            "total_users",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "histroy",
        sa.Column(
            "total_projects",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("histroy", "history_value")
    op.drop_column("histroy", "history_key")
    # ### end Alembic commands ###
