"""fix project introduction length

Revision ID: b306477282a1
Revises: 599c54cee280
Create Date: 2025-07-21 18:04:36.099890

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "b306477282a1"
down_revision = "599c54cee280"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project",
        "summary",
        existing_type=mysql.VARCHAR(length=50),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "project",
        "introduction",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.String(length=1500),
        existing_nullable=True,
    )
    op.alter_column(
        "review",
        "content",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.String(length=1500),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "review",
        "content",
        existing_type=sa.String(length=1500),
        type_=mysql.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "project",
        "introduction",
        existing_type=sa.String(length=1500),
        type_=mysql.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "project",
        "summary",
        existing_type=sa.String(length=100),
        type_=mysql.VARCHAR(length=50),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
