"""delete code_submissions

Revision ID: 8f87f9c43aea
Revises: 60e3aaf301ce
Create Date: 2025-12-31 22:01:46.151267

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "8f87f9c43aea"
down_revision = "60e3aaf301ce"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project_url",
        "url_type",
        existing_type=mysql.ENUM(
            "ANDROID_STORE",
            "IOS_STORE",
            "FRONTEND_GITHUB",
            "BACKEND_GITHUB",
            "ANDROID_GITHUB",
            "WEBSITE",
            "IOS_GITHUB",
            "CRAWLER_GITHUB",
            "DATA_GITHUB",
            "BEHANCE",
        ),
        nullable=False,
    )
    op.alter_column(
        "recruiting",
        "generation",
        existing_type=mysql.VARCHAR(length=30),
        server_default=sa.text("0.0"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "recruiting",
        "generation",
        existing_type=mysql.VARCHAR(length=30),
        server_default=sa.text("(0.0)"),
        existing_nullable=False,
    )
    op.alter_column(
        "project_url",
        "url_type",
        existing_type=mysql.ENUM(
            "ANDROID_STORE",
            "IOS_STORE",
            "FRONTEND_GITHUB",
            "BACKEND_GITHUB",
            "ANDROID_GITHUB",
            "WEBSITE",
            "IOS_GITHUB",
            "CRAWLER_GITHUB",
            "DATA_GITHUB",
            "BEHANCE",
        ),
        nullable=True,
    )
    # ### end Alembic commands ###
