"""Add table:
member, project, recruiting, recruting_info,
review, seminar, sponsor, timeline, faq

Revision ID: dfb42ebdb879
Revises: cc8ee03dfd6e
Create Date: 2025-07-03 14:34:37.206398

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "dfb42ebdb879"
down_revision = "cc8ee03dfd6e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "faq",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question", sa.String(length=255), nullable=False),
        sa.Column("answer", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "histroy",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("total_projects", sa.Integer(), nullable=False),
        sa.Column("total_users", sa.Integer(), nullable=False),
        sa.Column("total_members", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "member",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=30), nullable=False),
        sa.Column("last_name", sa.String(length=30), nullable=False),
        sa.Column("department", sa.String(length=50), nullable=True),
        sa.Column("college", sa.String(length=50), nullable=True),
        sa.Column("phone_number", sa.String(length=30), nullable=True),
        sa.Column("github_id", sa.String(length=30), nullable=True),
        sa.Column("generation", sa.String(length=30), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "seminar",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=30), nullable=False),
        sa.Column("content", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sponsor",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("amount", sa.String(length=30), nullable=False),
        sa.Column("email", sa.String(length=30), nullable=True),
        sa.Column("phone_number", sa.String(length=30), nullable=True),
        sa.Column("sponsored_date", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "timeline",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=30), nullable=False),
        sa.Column("content", sa.String(length=255), nullable=True),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("summary", sa.String(length=50), nullable=True),
        sa.Column("introduction", sa.String(length=255), nullable=True),
        sa.Column("thumbnail_url", sa.String(length=255), nullable=True),
        sa.Column("leader_id", sa.Integer(), nullable=False),
        sa.Column("is_service", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["leader_id"],
            ["member.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recruiting_info",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("info_num", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("date_info", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recruiting_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recruiting_id"],
            ["recruiting.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "review",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=30), nullable=False),
        sa.Column("content", sa.String(length=255), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["member.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project_member_association",
        sa.Column("member_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["member.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
    )
    op.create_table(
        "project_url",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_url")
    op.drop_table("project_member_association")
    op.drop_table("review")
    op.drop_table("recruiting_info")
    op.drop_table("project")
    op.drop_table("timeline")
    op.drop_table("sponsor")
    op.drop_table("seminar")
    op.drop_table("member")
    op.drop_table("histroy")
    op.drop_table("faq")
    # ### end Alembic commands ###
