"""add table pre_registration, project image urls

Revision ID: f1b48402a49c
Revises: dfb42ebdb879
Create Date: 2025-07-04 09:24:20.626606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "f1b48402a49c"
down_revision = "dfb42ebdb879"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_image_url",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("timeline", "content")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "timeline", sa.Column("content", mysql.VARCHAR(length=255), nullable=True)
    )
    op.drop_table("project_image_url")
    # ### end Alembic commands ###
