"""add unique constraint in table RecruitingInfo

Revision ID: 452f1da1cdd4
Revises: 2a2274e82630
Create Date: 2025-07-07 17:59:08.832561

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "452f1da1cdd4"
down_revision = "2a2274e82630"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uk_recruiting_info_num", "recruiting_info", ["recruiting_id", "info_num"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uk_recruiting_info_num", "recruiting_info", type_="unique")
    # ### end Alembic commands ###
