"""fix project url

Revision ID: a6ed99114b92
Revises: 9dd2ff558a82
Create Date: 2025-07-19 23:41:02.400446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "a6ed99114b92"
down_revision = "9dd2ff558a82"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_image",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("object_key", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("project_image_url")
    op.alter_column(
        "timeline",
        "group",
        existing_type=mysql.ENUM("ROOKIES", "PROGRAMMERS", "DESIGNERS"),
        type_=sa.Enum("ROOKIE", "PROGRAMMER", "DESIGNER", name="timelinegrouptype"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "timeline",
        "group",
        existing_type=sa.Enum(
            "ROOKIE", "PROGRAMMER", "DESIGNER", name="timelinegrouptype"
        ),
        type_=mysql.ENUM("ROOKIES", "PROGRAMMERS", "DESIGNERS"),
        existing_nullable=False,
    )
    op.create_table(
        "project_image_url",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("project_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("url", mysql.VARCHAR(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["project.id"], name="project_image_url_ibfk_1"
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.drop_table("project_image")
    # ### end Alembic commands ###
