"""add auth info

Revision ID: 13ccaabc3ec3
Revises: c2493af16868
Create Date: 2025-11-03 00:10:52.924678

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "13ccaabc3ec3"
down_revision = "c2493af16868"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blocked_token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("user", sa.Column("username", sa.String(length=50), nullable=False))
    op.add_column("user", sa.Column("password", sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "password")
    op.drop_column("user", "username")
    op.drop_table("blocked_token")
    # ### end Alembic commands ###
