"""project foreign key 명시적 지정

Revision ID: 8b0405748e11
Revises: 86732184f087
Create Date: 2025-10-05 16:07:10.202786

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "8b0405748e11"
down_revision = "86732184f087"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "thumbnail_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project", sa.Column("thumbnail_url", mysql.VARCHAR(length=255), nullable=True)
    )
    # ### end Alembic commands ###
