"""remove ProjectMember table and leader field

Revision ID: 2a2274e82630
Revises: f656d4e56c64
Create Date: 2025-07-06 22:29:11.865019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "2a2274e82630"
down_revision = "f656d4e56c64"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_member")
    op.add_column("member", sa.Column("position", sa.String(length=50), nullable=True))
    op.drop_constraint("project_ibfk_1", "project", type_="foreignkey")
    op.drop_column("project", "leader_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column("leader_id", mysql.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key("project_ibfk_1", "project", "member", ["leader_id"], ["id"])
    op.drop_column("member", "position")
    op.create_table(
        "project_member",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("project_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("member_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("member_name", mysql.VARCHAR(length=30), nullable=False),
        sa.Column("position", mysql.VARCHAR(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["member_id"], ["member.id"], name="project_member_ibfk_1"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["project.id"], name="project_member_ibfk_2"
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
