"""add is_thumbnail attribute in ProjectImage

Revision ID: c2493af16868
Revises: c29ee28051da
Create Date: 2025-10-05 16:57:31.012572

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "c2493af16868"
down_revision = "c29ee28051da"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "thumbnail_url")
    op.add_column(
        "project_image", sa.Column("is_thumbnail", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_image", "is_thumbnail")
    op.add_column(
        "project", sa.Column("thumbnail_url", mysql.VARCHAR(length=255), nullable=True)
    )
    # ### end Alembic commands ###
