"""empty message

Revision ID: 0485bca82700
Revises: 12665783c993
Create Date: 2025-09-29 00:47:52.758099

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0485bca82700"
down_revision = "12665783c993"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("formed_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "formed_at")
    # ### end Alembic commands ###
