"""fix seminar table

Revision ID: 84b2b60d89a6
Revises: 5b0d638c64db
Create Date: 2025-07-09 10:56:31.259848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "84b2b60d89a6"
down_revision = "5b0d638c64db"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "seminar",
        sa.Column(
            "seminar_type",
            sa.Enum(
                "SPRING", "FAST_API", "FRONTEND", "ANDROID", "IOS", name="seminartype"
            ),
            nullable=False,
        ),
    )
    op.add_column("seminar", sa.Column("curriculum_info", sa.Text(), nullable=False))
    op.add_column("seminar", sa.Column("prerequisite_info", sa.Text(), nullable=False))
    op.add_column("seminar", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.drop_column("seminar", "title")
    op.drop_column("seminar", "content")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "seminar", sa.Column("content", mysql.VARCHAR(length=255), nullable=False)
    )
    op.add_column(
        "seminar", sa.Column("title", mysql.VARCHAR(length=30), nullable=False)
    )
    op.drop_column("seminar", "is_active")
    op.drop_column("seminar", "prerequisite_info")
    op.drop_column("seminar", "curriculum_info")
    op.drop_column("seminar", "seminar_type")
    # ### end Alembic commands ###
