"""change member position type

Revision ID: 5b0d638c64db
Revises: 452f1da1cdd4
Create Date: 2025-07-07 18:15:47.298900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "5b0d638c64db"
down_revision = "452f1da1cdd4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "member",
        "position",
        existing_type=mysql.VARCHAR(length=50),
        type_=sa.Enum("FRONTEND", "BACKEND", "DESIGNER", name="position"),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "member",
        "position",
        existing_type=sa.Enum("FRONTEND", "BACKEND", "DESIGNER", name="position"),
        type_=mysql.VARCHAR(length=50),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
