"""add field service_type & is_active in project table, add field generation in recruiting table

Revision ID: 066dac40ece1
Revises: f1b48402a49c
Create Date: 2025-07-06 17:01:11.704940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "066dac40ece1"
down_revision = "f1b48402a49c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_member",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("member_name", sa.String(length=30), nullable=False),
        sa.Column("position", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["member.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("project_member_association")
    op.add_column(
        "project",
        sa.Column(
            "service_type",
            sa.Enum("SERVICE", "STUDY", name="projecttype"),
            nullable=False,
        ),
    )
    op.add_column("project", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.drop_column("project", "is_service")
    op.add_column(
        "project_url", sa.Column("title", sa.String(length=50), nullable=False)
    )
    op.add_column(
        "recruiting",
        sa.Column(
            "generation",
            sa.String(length=30),
            server_default=sa.text("0.0"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recruiting", "generation")
    op.drop_column("project_url", "title")
    op.add_column(
        "project",
        sa.Column(
            "is_service",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("project", "is_active")
    op.drop_column("project", "service_type")
    op.create_table(
        "project_member_association",
        sa.Column("member_id", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("project_id", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["member_id"], ["member.id"], name="project_member_association_ibfk_1"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["project.id"], name="project_member_association_ibfk_2"
        ),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.drop_table("project_member")
    # ### end Alembic commands ###
