"""add TimelineCategory table

Revision ID: c9b5e993e78b
Revises: 8964bb6498ca
Create Date: 2025-07-17 15:17:13.718063

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "c9b5e993e78b"
down_revision = "8964bb6498ca"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "timeline_category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("timeline", sa.Column("category_id", sa.Integer(), nullable=False))
    op.add_column(
        "timeline",
        sa.Column(
            "group",
            sa.Enum("ROOKIES", "PROGRAMMERS", "DESIGNERS", name="timelinegrouptype"),
            nullable=False,
        ),
    )
    op.create_foreign_key(
        None, "timeline", "timeline_category", ["category_id"], ["id"]
    )
    op.drop_column("timeline", "category")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "timeline", sa.Column("category", mysql.VARCHAR(length=30), nullable=False)
    )
    op.drop_constraint(None, "timeline", type_="foreignkey")
    op.drop_column("timeline", "group")
    op.drop_column("timeline", "category_id")
    op.drop_table("timeline_category")
    # ### end Alembic commands ###
