"""fix project url type

Revision ID: 8964bb6498ca
Revises: d7157419824c
Create Date: 2025-07-15 00:58:52.147111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "8964bb6498ca"
down_revision = "d7157419824c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("history_key", sa.String(length=50), nullable=False),
        sa.Column("history_value", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("histroy")
    op.add_column(
        "project_url",
        sa.Column(
            "url_type",
            sa.Enum(
                "ANDROID_STORE",
                "IOS_STORE",
                "FRONTEND_GITHUB",
                "BACKEND_GITHUB",
                "ANDROID_GITHUB",
                "WEBSITE",
                "IOS_GITHUB",
                "CRAWLER_GITHUB",
                "BEHANCE",
                name="projecturltype",
            ),
            nullable=False,
        ),
    )
    op.drop_column("project_url", "title")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_url", sa.Column("title", mysql.VARCHAR(length=50), nullable=False)
    )
    op.drop_column("project_url", "url_type")
    op.create_table(
        "histroy",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("history_key", mysql.VARCHAR(length=50), nullable=False),
        sa.Column("history_value", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    op.drop_table("history")
    # ### end Alembic commands ###
