"""fix sponsor amount & sponsored_date type

Revision ID: 16b579609e97
Revises: 4869ce051b80
Create Date: 2025-08-25 21:36:23.655109

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "16b579609e97"
down_revision = "4869ce051b80"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sponsor",
        "amount",
        existing_type=mysql.VARCHAR(length=30),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sponsor",
        "amount",
        existing_type=sa.Integer(),
        type_=mysql.VARCHAR(length=30),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
