"""add introduction field at member table

Revision ID: 22f4d37c8e9f
Revises: e974b1acbdc9
Create Date: 2025-07-10 16:41:08.160574

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "22f4d37c8e9f"
down_revision = "e974b1acbdc9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "member", sa.Column("introduction", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("member", "introduction")
    # ### end Alembic commands ###
