"""add DATA_GITHUB in ProjectURLType

Revision ID: 564952e2cd49
Revises: c2493af16868
Create Date: 2025-11-12 23:03:32.895041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "564952e2cd49"
down_revision = "c2493af16868"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project_url",
        "url_type",
        existing_type=mysql.ENUM(
            "ANDROID_STORE",
            "IOS_STORE",
            "FRONTEND_GITHUB",
            "BACKEND_GITHUB",
            "ANDROID_GITHUB",
            "WEBSITE",
            "IOS_GITHUB",
            "CRAWLER_GITHUB",
            "BEHANCE",
        ),
        type_=mysql.ENUM(
            "ANDROID_STORE",
            "IOS_STORE",
            "FRONTEND_GITHUB",
            "BACKEND_GITHUB",
            "ANDROID_GITHUB",
            "WEBSITE",
            "IOS_GITHUB",
            "CRAWLER_GITHUB",
            "DATA_GITHUB",
            "BEHANCE",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project_url",
        "url_type",
        existing_type=mysql.ENUM(
            "ANDROID_STORE",
            "IOS_STORE",
            "FRONTEND_GITHUB",
            "BACKEND_GITHUB",
            "ANDROID_GITHUB",
            "WEBSITE",
            "IOS_GITHUB",
            "CRAWLER_GITHUB",
            "DATA_GITHUB",
            "BEHANCE",
        ),
        type_=mysql.ENUM(
            "ANDROID_STORE",
            "IOS_STORE",
            "FRONTEND_GITHUB",
            "BACKEND_GITHUB",
            "ANDROID_GITHUB",
            "WEBSITE",
            "IOS_GITHUB",
            "CRAWLER_GITHUB",
            "BEHANCE",
        ),
    )
    # ### end Alembic commands ###
