"""add is_uploaded field

Revision ID: 599c54cee280
Revises: a6ed99114b92
Create Date: 2025-07-20 00:19:05.269601

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "599c54cee280"
down_revision = "a6ed99114b92"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_image", sa.Column("is_uploaded", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_image", "is_uploaded")
    # ### end Alembic commands ###
