"""fix enum type

Revision ID: 12665783c993
Revises: f1532cef4ac5
Create Date: 2025-09-14 22:11:40.030127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "12665783c993"
down_revision = "f1532cef4ac5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "member",
        "position",
        existing_type=mysql.ENUM("FRONTEND", "BACKEND", "DESIGNER"),
        type_=mysql.ENUM("FRONTEND", "BACKEND", "DESIGNER", "ANDROID", "IOS"),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
