"""discord member

Revision ID: ff334b61552d
Revises: e57751b758ee
Create Date: 2026-07-17 11:25:17.355055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff334b61552d'
down_revision = 'e57751b758ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_member',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('discord_id', sa.String(length=255), nullable=False),
    sa.Column('slack_user_id', sa.String(length=255), nullable=True),
    sa.Column('github_username', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discord_member')
    # ### end Alembic commands ###
