"""empty message

Revision ID: e57751b758ee
Revises: 4b0f9d2e7a61
Create Date: 2026-07-13 10:36:05.218603

"""

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "e57751b758ee"
down_revision = "4b0f9d2e7a61"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "code_submission",
        "language",
        existing_type=mysql.ENUM(
            "C",
            "CPP",
            "JAVA",
            "JAVASCRIPT",
            "PYTHON",
            "RUBY",
            "GO",
            "TYPESCRIPT",
            "KOTLIN",
            "SCALA",
            "SQL",
            "SWIFT",
        ),
        type_=mysql.ENUM(
            "C",
            "CPP",
            "JAVA",
            "JAVASCRIPT",
            "PYTHON",
            "RUBY",
            "GO",
            "TYPESCRIPT",
            "KOTLIN",
            "SCALA",
            "SQL",
            "SWIFT",
            "RUST",
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "code_submission",
        "language",
        existing_type=mysql.ENUM(
            "C",
            "CPP",
            "JAVA",
            "JAVASCRIPT",
            "PYTHON",
            "RUBY",
            "GO",
            "TYPESCRIPT",
            "KOTLIN",
            "SCALA",
            "SQL",
            "SWIFT",
            "RUST",
        ),
        type_=mysql.ENUM(
            "C",
            "CPP",
            "JAVA",
            "JAVASCRIPT",
            "PYTHON",
            "RUBY",
            "GO",
            "TYPESCRIPT",
            "KOTLIN",
            "SCALA",
            "SQL",
            "SWIFT",
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
