"""username 삭제

Revision ID: f94ad0ce6e8e
Revises: 60e3aaf301ce
Create Date: 2026-02-08 18:47:44.452486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "f94ad0ce6e8e"
down_revision = "60e3aaf301ce"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "username",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=50),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
